#!/bin/bash

export LOC="$PWD/out/target/product/u8500"
export ROOTDIR=$PWD

mkdir -p "$LOC"/temp
  
LEWA_OTA_FULL_PACKAGE="$LOC"/FULL_LeWa_ROM_U8500_$(date +%y.%m.%d.%H).zip

cd "$LOC"/temp
echo "extract update.zip"
#unzip -o -qq  "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip
unzip -o -qq "$LEWA_OTA_FULL_PACKAGE"
cp -fr "$ROOTDIR"/device/huawei/u8500/Repack-bootimg/boot.img ./boot.img
cp -fr "$ROOTDIR"/device/huawei/u8500/Repack-bootimg/boot.img "$LOC"/boot.img

echo "Making U8500 Compatible Update script"
cd "$LOC"

echo Zipping Package
cd "$LOC"/temp

#rm -rf "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip
#zip -9yr "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip * > /dev/null
rm -rf "$LEWA_OTA_FULL_PACKAGE"
zip -9yr "$LEWA_OTA_FULL_PACKAGE" * > /dev/null
cd "$LOC"

echo Cleanup...

rm -rf "$LOC"/temp
sh "$ROOTDIR"/vendor/cyanogen/tools/squisher

echo done
