#!/bin/bash

export LOC="$PWD/out/target/product/c8650"
export lewa="$PWD"

mkdir -p "$LOC"/temp

cd "$LOC"/temp
echo "extract update.zip"

#LOGNAME=$(cat /etc/passwd |awk -F':' '{print $1" "$3}'|grep \ $UID |awk '{print $1}')
LOGNAME=$(logname)

#echo $LOGNAME 

unzip -o -qq  "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip

echo "Making c8650 Compatible Update script"
cd "$LOC"
cd "$LOC"/temp/META-INF/com/google/android
rm -rf updater-script
cp "$lewa"/device/huawei/c8650/tools/updater-script "$LOC"/temp/META-INF/com/google/android/updater-script
cp "$lewa"/device/huawei/c8650/tools/boot_lewa.img "$LOC"/temp/boot_lewa.img
cp "$lewa"/device/huawei/c8650/tools/checklcd "$LOC"/temp/checklcd
echo Zipping Package
cd "$LOC"/temp
rm -rf "$LOC"/temp/recovery
rm -rf "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip
zip -9yr "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip * > /dev/null
cd "$LOC"


LEWA_OTA_FULL_PACKAGE="$LOC"/FULL_LeWa_ROM_C8650_$(date +%y.%m.%d.%H).zip
NEW_OTA_PACKAGE="$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip

#cp -fr $(NEW_OTA_PACKAGE)  $(LEWA_OTA_FULL_PACKAGE)
rm -fr "$LOC"/FULL_LeWa_ROM_C8650_$(date +%y.%m.%d.%H).zip

#sign
printf "Signing Lewa OTA package..."
java -Xmx512m \
	-jar "$lewa"/out/host/linux-x86/framework/signapk.jar \
	-w "$lewa"/build/target/product/security/testkey.x509.pem "$lewa"/build/target/product/security/testkey.pk8 \
	$NEW_OTA_PACKAGE $LEWA_OTA_FULL_PACKAGE
#	"$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip "$LOC"/#FULL_LeWa_ROM_C8650_$(date +%y.%m.%d.%H).zip 
echo


echo Cleanup...
rm -rf "$LOC"/temp
sh "$lewa"/vendor/cyanogen/tools/squisher
echo done
